=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.1.0/lib/LaTeXML/dtd/LaTeXML.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 /=====================================================================\ 
 |  LaTeXML.dtd                                                        |
 | Document Type for LaTeXML generated documents                       |
 |=====================================================================|
 | Part of LaTeXML:                                                    |
 |  Public domain software, produced as part of work done by the       |
 |  United States Government & not subject to copyright in the US.     |
 |=====================================================================|
 | Bruce Miller <bruce.miller@nist.gov>                        #_#     |
 | http://dlmf.nist.gov/LaTeXML/                              (o o)    |
 \=========================================================ooo==U==ooo=/
-->

<!ENTITY % Simple.class
        "textstyle | textup | textit | textsl | textsc | textmd | textbf | textrm | textsf | texttt 
         | emph | textsize | text | cite | ref ">
<!ENTITY % Inline.class
         "a | XMath">

<!-- kinda concerned about equation being only block -->
<!ENTITY % Block.class
         "p  | equation | figure | table  | tabular | centering | 
          itemize | enumerate | description">
<!ENTITY % Misc.class
         " graphics | quote | footnote | index">

<!-- These can be overridden to add more elements. -->
<!ENTITY % Simple.extra "">
<!ENTITY % Inline.extra "">
<!ENTITY % Block.extra  "">
<!ENTITY % Misc.extra   "">

<!ENTITY % Simple.mix
      "%Simple.class; %Simple.extra;">
<!ENTITY % Inline.mix
      "%Simple.class; %Simple.extra; | %Inline.class; %Inline.extra; | %Misc.class; %Misc.extra;">
<!ENTITY % Block.mix "%Block.class; %Block.extra; | %Misc.class; %Misc.extra;">
<!ENTITY % Flow.mix
       "%Simple.class; %Simple.extra; | %Inline.class; %Inline.extra;
        | %Block.class; %Block.extra; | %Misc.class; %Misc.extra;">

<!-- ======================================================================
     Math level
     Really MathML !!!
     ====================================================================== -->
<!-- Include MathML 2 -->


<!ENTITY % NS.prefixed "INCLUDE">
<!ENTITY % NamespaceDecl.attrib "xmlns:m CDATA #IMPLIED"> <!-- ??? -->
<!ENTITY % MathML.dtd PUBLIC "-//W3C//DTD MathML 2.0//EN" "mathml2.dtd">
%MathML.dtd;

<!ENTITY % Equation.extra "">

<!ELEMENT equation (XMath | tabular | punct | index %Equation.extra;)*>
<!ATTLIST equation
          label ID #IMPLIED
          refnum CDATA #IMPLIED>

<!-- Hmm, tabular ? -->
<!ENTITY % XMath.model "XMApp | XMTok | XMHint | XMArg | XMWrap | XMDual | %Simple.class;">
<!ELEMENT XMath (%XMath.model; | tabular | m:math)*>
<!ATTLIST XMath
          mode (display|inline) #IMPLIED
          tex CDATA #IMPLIED
          prefix CDATA #IMPLIED
          mathimage CDATA #IMPLIED
          width  CDATA #IMPLIED
          height CDATA #IMPLIED>

<!ELEMENT PMNode (%XMath.model;)*>
<!ATTLIST PMNode
          class CDATA #REQUIRED
          value CDATA #IMPLIED>


<!ELEMENT XMApp (%XMath.model;)*>
<!ATTLIST XMApp
          POS     CDATA #IMPLIED
          name    CDATA #IMPLIED
	  stackscripts CDATA #IMPLIED
          tex     CDATA #IMPLIED>
<!ELEMENT XMDual ((%XMath.model;), (%XMath.model;))>
<!ATTLIST XMDual
          POS     CDATA #IMPLIED
          tex     CDATA #IMPLIED>
<!ELEMENT XMTok (#PCDATA)*>
<!ATTLIST XMTok
          name    CDATA #IMPLIED
          POS     CDATA #IMPLIED
          font    CDATA #IMPLIED
          style   CDATA #IMPLIED
          size    CDATA #IMPLIED
          tex     CDATA #IMPLIED
	  stackscripts CDATA #IMPLIED>

<!ELEMENT XMHint EMPTY>
<!ATTLIST XMHint
          name    CDATA #IMPLIED
          POS     CDATA #IMPLIED
          style   CDATA #IMPLIED
          tex     CDATA #IMPLIED>

<!ELEMENT XMWrap (%XMath.model;)*>
<!ATTLIST XMWrap
          name    CDATA #IMPLIED
          POS     CDATA #IMPLIED
          style   CDATA #IMPLIED
          tex     CDATA #IMPLIED>
<!ELEMENT XMArg (%XMath.model;)*>
<!ATTLIST XMArg
          rule   CDATA #IMPLIED>

<!ELEMENT style (#PCDATA)*>
<!ATTLIST style
          style CDATA #IMPLIED>
<!ELEMENT punct (#PCDATA)*>
<!-- ======================================================================
     Document Structure
     ====================================================================== -->

<!ENTITY % Frontmatter.class "title | toctitle | author | creationdate">
<!ENTITY % Frontmatter.extra "">
<!ENTITY % Frontmatter.mix "%Frontmatter.class; %Frontmatter.extra;">

<!ENTITY % Sectitle.class "title | toctitle | author">
<!ENTITY % Sectitle.extra "">
<!ENTITY % Sectitle.mix "%Sectitle.class; %Sectitle.extra;">


<!-- If you want to rearrange the overall document structure define
     define.structure to be IGNORE, then include a modified version of
     the following. -->
<!ENTITY % define.structure  "INCLUDE" >
<![%define.structure;[

<!ELEMENT document ((%Frontmatter.mix;)*, section*, bibliography?, appendix*)>
<!ELEMENT section       ((%Sectitle.mix;)*, (%Block.mix; | subsection | paragraph)*)>
<!ELEMENT appendix      ((%Sectitle.mix;)*, (%Block.mix; | subsection | paragraph)*)>
<!ELEMENT subsection    ((%Sectitle.mix;)*, (%Block.mix; | subsubsection | paragraph)*)>
<!ELEMENT subsubsection ((%Sectitle.mix;)*, (%Block.mix; | paragraph)*)>
<!ELEMENT paragraph     ((%Sectitle.mix;)*, (%Block.mix;)*)>

]]>

<!ELEMENT title    (#PCDATA | %Inline.mix;)* >
<!ELEMENT toctitle (#PCDATA | %Inline.mix;)* >
<!ELEMENT author   (#PCDATA | %Inline.mix;)* >
<!ELEMENT creationdate (#PCDATA | %Inline.mix;)* >

<!ELEMENT p        (#PCDATA | %Inline.mix;)*>

<!ENTITY % section-attr "
          label ID #IMPLIED
          refnum CDATA #IMPLIED">

<!ATTLIST document %section-attr;>
<!ATTLIST chapter %section-attr;>
<!ATTLIST part %section-attr;>
<!ATTLIST section %section-attr;>
<!ATTLIST appendix %section-attr;>
<!ATTLIST subsection %section-attr;>
<!ATTLIST subsubsection %section-attr;>
<!ATTLIST paragraph %section-attr;>
<!-- <!ATTLIST p %section-attr;> -->

<!-- ======================================================================
     Block Elements
     ====================================================================== -->
<!ELEMENT figure (%Block.mix; | caption | toccaption)*>
<!ELEMENT table (%Block.mix; | caption | toccaption)*>
<!ATTLIST figure
          label  ID #IMPLIED
          placement CDATA #IMPLIED
          refnum CDATA #IMPLIED>
<!ATTLIST table
          label  ID #IMPLIED
          placement CDATA #IMPLIED
          refnum CDATA #IMPLIED>
<!ELEMENT caption (#PCDATA | %Inline.mix;)*>
<!ELEMENT toccaption (#PCDATA | %Inline.mix;)*>

<!-- tabular is basically cribbed from HTML4's table -->
<!ELEMENT tabular ((col*|colgroup*), thead?, tfoot?, (tbody | tr | hline)*)>
<!ATTLIST tabular
          pattern CDATA #IMPLIED
          frame   CDATA #IMPLIED
          rules   CDATA #IMPLIED>
<!ELEMENT colgroup (col)*>
<!ATTLIST colgroup
          span  CDATA #IMPLIED
          align CDATA #IMPLIED>
<!ATTLIST col
          span  CDATA #IMPLIED
          align CDATA #IMPLIED>

<!ELEMENT thead (tr)*>
<!ELEMENT tfoot (tr)*>
<!ELEMENT tbody (tr)*>
<!ELEMENT tr (td | th)*>

<!ELEMENT th (#PCDATA | %Inline.mix;)*>
<!ATTLIST th
          rowpan CDATA #IMPLIED
          colspan CDATA #IMPLIED
          align CDATA #IMPLIED
          pattern CDATA #IMPLIED>

<!ELEMENT td (#PCDATA | %Inline.mix;)*>
<!ATTLIST td
          rowspan CDATA #IMPLIED
          colspan CDATA #IMPLIED
          align CDATA #IMPLIED
          pattern CDATA #IMPLIED>

<!ELEMENT hline EMPTY>

<!ELEMENT centering (%Flow.mix;)*>
<!ELEMENT itemize (item)*>
<!ELEMENT enumerate (item)*>
<!ELEMENT description (item)*>
<!ELEMENT item (#PCDATA | tag | %Flow.mix; )*>
<!ELEMENT tag (#PCDATA | %Inline.mix;)*>

<!ELEMENT graphics EMPTY>
<!ATTLIST graphics
          graphic CDATA #REQUIRED
          options CDATA #IMPLIED
          src     CDATA #IMPLIED
          width   CDATA #IMPLIED
          height  CDATA #IMPLIED>

<!-- ======================================================================
     Inline Elements
     ====================================================================== -->
<!ELEMENT textstyle (#PCDATA | %Inline.mix;)*>
<!ATTLIST textstyle
	  font CDATA #IMPLIED>

<!ELEMENT textup (#PCDATA | %Inline.mix;)*>
<!ELEMENT textit (#PCDATA | %Inline.mix;)*>
<!ELEMENT emph   (#PCDATA | %Inline.mix;)*>
<!ELEMENT textsl (#PCDATA | %Inline.mix;)*>
<!ELEMENT textsc (#PCDATA | %Inline.mix;)*>
<!ELEMENT textmd (#PCDATA | %Inline.mix;)*>
<!ELEMENT textbf (#PCDATA | %Inline.mix;)*>
<!ELEMENT textrm (#PCDATA | %Inline.mix;)*>
<!ELEMENT textsf (#PCDATA | %Inline.mix;)*>
<!ELEMENT texttt (#PCDATA | %Inline.mix;)*>
<!ELEMENT text (#PCDATA | %Inline.mix;)*>
<!ELEMENT textsize (#PCDATA | %Inline.mix;)*>
<!ATTLIST textsize
          size CDATA #REQUIRED>


<!ELEMENT cite (citepre?,citepost?)>
<!ATTLIST cite
          ref CDATA #REQUIRED
          style (intext|parenthetic) #IMPLIED
          show CDATA #IMPLIED>
<!ELEMENT citepre (#PCDATA | %Inline.mix;)*>
<!ELEMENT citepost (#PCDATA | %Inline.mix;)*>

<!ELEMENT a  (#PCDATA | %Inline.mix;)*>
<!ATTLIST a
          href CDATA #REQUIRED>
<!-- ======================================================================
     Misc Elements
     can appear in block or inline contexts
     ====================================================================== -->

<!ELEMENT quote  (#PCDATA | %Inline.mix;)*>
<!ELEMENT footnote  (#PCDATA | %Inline.mix;)*>
<!ATTLIST footnote
          footnotemark CDATA #IMPLIED>
<!-- ======================================================================
     Meta data
     ====================================================================== -->

<!ELEMENT ref   EMPTY>
<!ATTLIST ref
          labelref CDATA #REQUIRED>
<!ELEMENT index (indexphrase*)>
<!ELEMENT indexphrase (#PCDATA | %Inline.mix;)*>

<!-- ======================================================================
     Bibliography
     ====================================================================== -->


<!ELEMENT bibliography (biblist*)>
<!ATTLIST bibliography
          files CDATA #REQUIRED>

<!ELEMENT biblist (bibentry)*>
<!-- prefix all elements with bib- to avoid conflicts
     Alternatively, separate DTD/namespace ? -->
   
<!ELEMENT bibentry (bib-author | bib-editor | bib-translator |
               bib-title | bib-subtitle | bib-booktitle |
               bib-journal | bib-series | bib-conference | bib-publisher |
               bib-organization | bib-institution | bib-address |
               bib-volume | bib-number | bib-pages | bib-part | bib-date | bib-edition |
               bib-status | bib-type |
               bib-issn | bib-doi | bib-isbn | bib-review | bib-mrnumber |
               bib-language |
               bib-url | bib-code_url | bib-eprint | bib-preprint | bib-note )*>
<!ATTLIST bibentry
          key CDATA #REQUIRED
          type CDATA #REQUIRED>
<!-- hyphenation |  xref | label | setup | name  -->

<!--
<!ELEMENT bib-author (surname, givenname?, giveninitials?, jrname?)>
<!ELEMENT bib-editor (surname, givenname?, giveninitials?, jrname?)>
<!ELEMENT surname (#PCDATA | %Inline.mix;)*>
<!ELEMENT givenname (#PCDATA | %Inline.mix;)*>
<!ELEMENT giveninitials (#PCDATA | %Inline.mix;)*>
<!ELEMENT jrname (#PCDATA | %Inline.mix;)*>
-->
<!ELEMENT bib-author (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-editor (#PCDATA | %Inline.mix;)*>

<!ELEMENT bib-translator (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-title (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-subtitle (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-booktitle (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-journal (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-series (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-conference (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-publisher (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-organization (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-institution (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-address (#PCDATA | %Inline.mix;)*>

<!ELEMENT bib-volume (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-number (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-pages (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-part (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-date (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-edition (#PCDATA | %Inline.mix;)*>

<!ELEMENT bib-status (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-type (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-issn (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-isbn (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-doi (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-review (#PCDATA | %Inline.mix; | bib-mr)*>
<!ELEMENT bib-mr (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-mrnumber (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-language (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-url (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-code_url (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-eprint (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-preprint (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-note (#PCDATA | %Inline.mix;)*>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.3.1/t/mathgroup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class='article'?>
<document xmlns='http://dlmf.nist.gov/LaTeXML'>
  <section>
    <p>Expect Original : Original</p>
    <p>Expect a + Original: <XMath mode='inline' tex='a+\mbox{Original}'>
        <XMTok font='italic'>a</XMTok>
        <XMTok>+</XMTok>
        <text>Original</text>
      </XMath> </p>
    <p>Expect Original : Original</p>
    <p>Expect InBox + Original:  <text>InBox</text> + Original</p>
    <p>Expect Original : Original</p>
    <p>Expect a + InlineMath: <XMath mode='inline' tex='a+\hbox{InlineMath}'>
        <XMTok font='italic'>a</XMTok>
        <XMTok>+</XMTok>
        <text>InlineMath</text>
      </XMath> </p>
    <p>Expect Original : Original</p>
    <p>Expect a + DisplayMath : </p>
    <equation>
      <XMath mode='display' tex='a+\hbox{DisplayMath}'>
        <XMTok font='italic'>a</XMTok>
        <XMTok>+</XMTok>
        <text>DisplayMath</text>
      </XMath>
    </equation>
    <p>Expect Original : Original</p>
    <p>Expect a + InText + InlineMath: <XMath mode='inline' tex='a+\hbox{InText}+\hbox{InlineMath}'>
        <XMTok font='italic'>a</XMTok>
        <XMTok>+</XMTok>
        <text>InText</text>
        <XMTok>+</XMTok>
        <text>InlineMath</text>
      </XMath> </p>
    <p>Expect Original : Original</p>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.5.0/t/math/choose.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class="article"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <section id="S1" refnum="1">
    <title>Testing Choose</title>
    <para id="S1.p1">
      <p>beep hello, BEEP. beep.</p>
    </para>
    <para id="S1.p2">
      <p>1. <Math mode="inline" tex="a+b" text="a + b"><XMath><XMApp><XMTok role="ADDOP">+</XMTok><XMTok role="UNKNOWN" font="italic">a</XMTok><XMTok role="UNKNOWN" font="italic">b</XMTok></XMApp></XMath></Math></p>
    </para>
    <para id="S1.p3">
      <p>2. <Math mode="inline" tex="a\choose b" text="binomial@(a, b)"><XMath><XMApp><XMTok name="binomial"/><XMTok role="UNKNOWN" font="italic">a</XMTok><XMTok role="UNKNOWN" font="italic">b</XMTok></XMApp></XMath></Math></p>
    </para>
    <para id="S1.p4">
      <p>3. <Math mode="inline" tex="a+{b\choose c}+d" text="a + binomial@(b, c) + d"><XMath><XMApp><XMTok role="ADDOP">+</XMTok><XMTok role="UNKNOWN" font="italic">a</XMTok><XMApp><XMTok name="binomial"/><XMTok role="UNKNOWN" font="italic">b</XMTok><XMTok role="UNKNOWN" font="italic">c</XMTok></XMApp><XMTok role="UNKNOWN" font="italic">d</XMTok></XMApp></XMath></Math></p>
    </para>
    <para id="S1.p5">
      <p>4. <Math mode="inline" tex="a+{b\choose c}+d" text="a + binomial@(b, c) + d"><XMath><XMApp><XMTok role="ADDOP">+</XMTok><XMTok role="UNKNOWN" font="italic">a</XMTok><XMApp><XMTok name="binomial"/><XMTok role="UNKNOWN" font="italic">b</XMTok><XMTok role="UNKNOWN" font="italic">c</XMTok></XMApp><XMTok role="UNKNOWN" font="italic">d</XMTok></XMApp></XMath></Math></p>
    </para>
    <para id="S1.p6">
      <p>5. <Math mode="inline" tex="a+{b\choose c}+d" text="a + binomial@(b, c) + d"><XMath><XMApp><XMTok role="ADDOP">+</XMTok><XMTok role="UNKNOWN" font="italic">a</XMTok><XMApp><XMTok name="binomial"/><XMTok role="UNKNOWN" font="italic">b</XMTok><XMTok role="UNKNOWN" font="italic">c</XMTok></XMApp><XMTok role="UNKNOWN" font="italic">d</XMTok></XMApp></XMath></Math></p>
    </para>
    <para id="S1.p7">
      <p>6. <Math mode="inline" tex="a+b\choose c+d" text="binomial@(a + b, c + d)"><XMath><XMApp><XMTok name="binomial"/><XMApp><XMTok role="ADDOP">+</XMTok><XMTok role="UNKNOWN" font="italic">a</XMTok><XMTok role="UNKNOWN" font="italic">b</XMTok></XMApp><XMApp><XMTok role="ADDOP">+</XMTok><XMTok role="UNKNOWN" font="italic">c</XMTok><XMTok role="UNKNOWN" font="italic">d</XMTok></XMApp></XMApp></XMath></Math></p>
    </para>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.5.1/t/parse/sets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class="article"?>
<?latexml package="latexml"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <section>
    <para id="p1">
      <equation id="Ex1">
        <Math mode="display" tex="\{ a\}" text="Set@(a)">
          <XMath>
            <XMApp>
              <XMTok name="Set" role="FENCED" argclose="}" argopen="{"/>
              <XMTok role="ID" font="italic">a</XMTok>
            </XMApp>
          </XMath>
        </Math>
      </equation>
      <equation id="Ex2">
        <Math mode="display" tex="\{ a:a\in b\}" text="ConditionalSet@(a, a in b)">
          <XMath>
            <XMApp>
              <XMTok name="ConditionalSet" role="FENCED" argclose="}" argopen="{" separators=";"/>
              <XMTok role="ID" font="italic">a</XMTok>
              <XMApp>
                <XMTok name="in" role="RELOP">∈</XMTok>
                <XMTok role="ID" font="italic">a</XMTok>
                <XMTok role="ID" font="italic">b</XMTok>
              </XMApp>
            </XMApp>
          </XMath>
        </Math>
      </equation>
      <equation id="Ex3">
        <Math mode="display" tex="\{ a|a\in b\}" text="ConditionalSet@(a, a in b)">
          <XMath>
            <XMApp>
              <XMTok name="ConditionalSet" role="FENCED" argclose="}" argopen="{" separators="|"/>
              <XMTok role="ID" font="italic">a</XMTok>
              <XMApp>
                <XMTok name="in" role="RELOP">∈</XMTok>
                <XMTok role="ID" font="italic">a</XMTok>
                <XMTok role="ID" font="italic">b</XMTok>
              </XMApp>
            </XMApp>
          </XMath>
        </Math>
      </equation>
    </para>
    <para id="p2">
      <equation id="Ex4">
        <Math mode="display" tex="\{ a|a\in b\} _{{c=0}}" text="(ConditionalSet@(a, a in b)) _ (c = 0)">
          <XMath>
            <XMApp>
              <XMTok name="Subscript" role="SUBSCRIPT"/>
              <XMApp>
                <XMTok name="ConditionalSet" role="FENCED" argclose="}" argopen="{" separators="|"/>
                <XMTok role="ID" font="italic">a</XMTok>
                <XMApp>
                  <XMTok name="in" role="RELOP">∈</XMTok>
                  <XMTok role="ID" font="italic">a</XMTok>
                  <XMTok role="ID" font="italic">b</XMTok>
                </XMApp>
              </XMApp>
              <XMApp>
                <XMTok role="RELOP">=</XMTok>
                <XMTok role="ID" font="italic">c</XMTok>
                <XMTok role="NUMBER">0</XMTok>
              </XMApp>
            </XMApp>
          </XMath>
        </Math>
      </equation>
    </para>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.3.0/t/scopemacro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class="article"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <section refnum="1">
    <title>One</title>
    <p>Expect Section 1:Section 1.
</p>
  </section>
  <section refnum="2">
    <title>Two</title>
    <p>Expect Unknown: Unknown.
</p>
    <equation refnum="1">
      <Math mode="display" tex="\mbox{Equation 1}=\mbox{Equation 1}" text="[Equation 1] = [Equation 1]">
        <XMath>
          <XMApp>
            <XMTok role="RELOP">=</XMTok>
            <text>Equation 1</text>
            <text>Equation 1</text>
          </XMApp>
        </XMath>
      </Math>
    </equation>
    <p>Expect Unknown: Unknown.
</p>
    <subsection refnum="2.1">
      <title>Two pt one</title>
      <p>Expect Subsection 2.1: Subsection 2.1</p>
    </subsection>
    <subsection refnum="2.2">
      <title>Two point two</title>
      <p>Expect Unknown: Unknown.
</p>
    </subsection>
    <subsection refnum="2.3" label="labelled">
      <title>Two point three</title>
      <p>Expect Labelled subsection: Labelled subsection</p>
    </subsection>
    <subsection refnum="2.4">
      <title>Two point four</title>
      <p>Expect Unknown: Unknown.
</p>
    </subsection>
  </section>
  <section refnum="3">
    <title>Three</title>
    <p>Expect Section 3:Section 3.
</p>
    <subsection refnum="3.1">
      <title>Three point one</title>
      <p>Expect Section 3: Section 3.
</p>
    </subsection>
  </section>
  <section refnum="4">
    <title>Four</title>
    <p>Expect Unknown: Unknown.
</p>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.2.99/t/simplemath.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class="article"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <section>
    <p>Inline math <Math mode="inline" tex="a+b" text="a + b"><XMath><XMApp><XMTok role="ADDOP">+</XMTok><XMTok role="ID" font="italic">a</XMTok><XMTok role="ID" font="italic">b</XMTok></XMApp></XMath></Math>.
</p>
    <equation>
      <Math mode="display" tex="a+b+123" text="a + b + 123">
        <XMath>
          <XMApp>
            <XMTok role="ADDOP">+</XMTok>
            <XMTok role="ID" font="italic">a</XMTok>
            <XMTok role="ID" font="italic">b</XMTok>
            <XMTok name="123" role="NUMBER">123</XMTok>
          </XMApp>
        </XMath>
      </Math>
    </equation>
    <equation>
      <Math mode="display" tex="a+b+f(123)" text="a + b + f@(123)">
        <XMath>
          <XMApp>
            <XMTok role="ADDOP">+</XMTok>
            <XMTok role="ID" font="italic">a</XMTok>
            <XMTok role="ID" font="italic">b</XMTok>
            <XMApp>
              <XMTok role="FUNCTION" argclose=")" argopen="(" font="italic">f</XMTok>
              <XMTok name="123" role="NUMBER">123</XMTok>
            </XMApp>
          </XMApp>
        </XMath>
      </Math>
    </equation>
    <equation>
      <Math mode="display" tex="f_{D}f(a+b)" text="f _ D * f@(a + b)">
        <XMath>
          <XMApp>
            <XMTok role="MULOP">⁢</XMTok>
            <XMApp>
              <XMTok name="Subscript" role="SUBSCRIPT"/>
              <XMTok role="ID" font="italic">f</XMTok>
              <XMTok role="ID" font="italic">D</XMTok>
            </XMApp>
            <XMApp>
              <XMTok role="FUNCTION" argclose=")" argopen="(" font="italic">f</XMTok>
              <XMApp>
                <XMTok role="ADDOP">+</XMTok>
                <XMTok role="ID" font="italic">a</XMTok>
                <XMTok role="ID" font="italic">b</XMTok>
              </XMApp>
            </XMApp>
          </XMApp>
        </XMath>
      </Math>
    </equation>
    <equation>
      <Math mode="display" tex="f_{1}(a+b)" text="f _ 1 * (a + b)">
        <XMath>
          <XMApp>
            <XMTok role="MULOP">⁢</XMTok>
            <XMApp>
              <XMTok name="Subscript" role="SUBSCRIPT"/>
              <XMTok role="ID" font="italic">f</XMTok>
              <XMTok role="NUMBER">1</XMTok>
            </XMApp>
            <XMApp open="(" close=")">
              <XMTok role="ADDOP">+</XMTok>
              <XMTok role="ID" font="italic">a</XMTok>
              <XMTok role="ID" font="italic">b</XMTok>
            </XMApp>
          </XMApp>
        </XMath>
      </Math>
    </equation>
    <equation>
      <Math mode="display" tex="\hat{f}a" text="hat@(f) * a">
        <XMath>
          <XMApp>
            <XMTok role="MULOP">⁢</XMTok>
            <XMApp role="ID">
              <XMTok name="hat" role="OVERACCENT">^</XMTok>
              <XMTok role="FUNCTION" font="italic">f</XMTok>
            </XMApp>
            <XMTok role="ID" font="italic">a</XMTok>
          </XMApp>
        </XMath>
      </Math>
    </equation>
  </section>
  <section refnum="1" label="sec:restricted">
    <title>Restricted</title>
    <equation>
      <Math mode="display" tex="a(x)+b(x)+123" text="a@(x) + b@(x) + 123">
        <XMath>
          <XMApp>
            <XMTok role="ADDOP">+</XMTok>
            <XMApp>
              <XMTok role="FUNCTION" argclose=")" argopen="(" font="italic">a</XMTok>
              <XMTok role="ID" font="italic">x</XMTok>
            </XMApp>
            <XMApp>
              <XMTok role="FUNCTION" argclose=")" argopen="(" font="italic">b</XMTok>
              <XMTok role="ID" font="italic">x</XMTok>
            </XMApp>
            <XMTok name="123" role="NUMBER">123</XMTok>
          </XMApp>
        </XMath>
      </Math>
    </equation>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.1.1/t/testover.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class='article'?>
<document xmlns='http://dlmf.nist.gov/LaTeXML'>
  <section refnum='1'>
    <title>Testing Over</title>
    <p><Math mode='inline' tex='abc \over def'>
        <XMath>
          <XMApp>
            <XMTok name='/' style='over'/>
            <XMArg>
              <XMTok font='italic'>a</XMTok>
              <XMTok font='italic'>b</XMTok>
              <XMTok font='italic'>c</XMTok>
            </XMArg>
            <XMArg>
              <XMTok font='italic'>d</XMTok>
              <XMTok font='italic'>e</XMTok>
              <XMTok font='italic'>f</XMTok>
            </XMArg>
          </XMApp>
        </XMath>
      </Math>
</p>
    <p><Math mode='inline' tex='a{bc \over de}f'>
        <XMath>
          <XMTok font='italic'>a</XMTok>
          <XMApp>
            <XMTok name='/' style='over'/>
            <XMArg>
              <XMTok font='italic'>b</XMTok>
              <XMTok font='italic'>c</XMTok>
            </XMArg>
            <XMArg>
              <XMTok font='italic'>d</XMTok>
              <XMTok font='italic'>e</XMTok>
            </XMArg>
          </XMApp>
          <XMTok font='italic'>f</XMTok>
        </XMath>
      </Math>
</p>
    <p><Math mode='inline' tex='a{bc \over de}f'>
        <XMath>
          <XMTok font='italic'>a</XMTok>
          <XMApp>
            <XMTok name='/' style='over'/>
            <XMArg>
              <XMTok font='italic'>b</XMTok>
              <XMTok font='italic'>c</XMTok>
            </XMArg>
            <XMArg>
              <XMTok font='italic'>d</XMTok>
              <XMTok font='italic'>e</XMTok>
            </XMArg>
          </XMApp>
          <XMTok font='italic'>f</XMTok>
        </XMath>
      </Math>
</p>
    <p><Math mode='inline' tex='a{bc \over de}f'>
        <XMath>
          <XMTok font='italic'>a</XMTok>
          <XMApp>
            <XMTok name='/' style='over'/>
            <XMArg>
              <XMTok font='italic'>b</XMTok>
              <XMTok font='italic'>c</XMTok>
            </XMArg>
            <XMArg>
              <XMTok font='italic'>d</XMTok>
              <XMTok font='italic'>e</XMTok>
            </XMArg>
          </XMApp>
          <XMTok font='italic'>f</XMTok>
        </XMath>
      </Math>
</p>
    <p><Math mode='inline' tex='a{bc \over de}f'>
        <XMath>
          <XMTok font='italic'>a</XMTok>
          <XMApp>
            <XMTok name='/' style='over'/>
            <XMArg>
              <XMTok font='italic'>b</XMTok>
              <XMTok font='italic'>c</XMTok>
            </XMArg>
            <XMArg>
              <XMTok font='italic'>d</XMTok>
              <XMTok font='italic'>e</XMTok>
            </XMArg>
          </XMApp>
          <XMTok font='italic'>f</XMTok>
        </XMath>
      </Math>
</p>
    <p><Math mode='inline' tex='a{bc \over d \over e}f'>
        <XMath>
          <XMTok font='italic'>a</XMTok>
          <XMApp>
            <XMTok name='/' style='over'/>
            <XMArg>
              <XMTok font='italic'>b</XMTok>
              <XMTok font='italic'>c</XMTok>
            </XMArg>
            <XMArg>
              <XMApp>
                <XMTok name='/' style='over'/>
                <XMArg>
                  <XMTok font='italic'>d</XMTok>
                </XMArg>
                <XMArg>
                  <XMTok font='italic'>e</XMTok>
                </XMArg>
              </XMApp>
            </XMArg>
          </XMApp>
          <XMTok font='italic'>f</XMTok>
        </XMath>
      </Math>
<Math mode='inline' tex='\{a\}'>
        <XMath>
          <XMTok>{</XMTok>
          <XMTok font='italic'>a</XMTok>
          <XMTok>}</XMTok>
        </XMath>
      </Math>
<Math mode='inline' tex='\left\{a\right\}'>
        <XMath>
          <XMTok POS='OPEN'>{</XMTok>
          <XMTok font='italic'>a</XMTok>
          <XMTok POS='CLOSE'>}</XMTok>
        </XMath>
      </Math>
</p>
  </section>
</document>
