=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.1.0/lib/LaTeXML/dtd/LaTeXML.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 /=====================================================================\ 
 |  LaTeXML.dtd                                                        |
 | Document Type for LaTeXML generated documents                       |
 |=====================================================================|
 | Part of LaTeXML:                                                    |
 |  Public domain software, produced as part of work done by the       |
 |  United States Government & not subject to copyright in the US.     |
 |=====================================================================|
 | Bruce Miller <bruce.miller@nist.gov>                        #_#     |
 | http://dlmf.nist.gov/LaTeXML/                              (o o)    |
 \=========================================================ooo==U==ooo=/
-->

<!ENTITY % Simple.class
        "textstyle | textup | textit | textsl | textsc | textmd | textbf | textrm | textsf | texttt 
         | emph | textsize | text | cite | ref ">
<!ENTITY % Inline.class
         "a | XMath">

<!-- kinda concerned about equation being only block -->
<!ENTITY % Block.class
         "p  | equation | figure | table  | tabular | centering | 
          itemize | enumerate | description">
<!ENTITY % Misc.class
         " graphics | quote | footnote | index">

<!-- These can be overridden to add more elements. -->
<!ENTITY % Simple.extra "">
<!ENTITY % Inline.extra "">
<!ENTITY % Block.extra  "">
<!ENTITY % Misc.extra   "">

<!ENTITY % Simple.mix
      "%Simple.class; %Simple.extra;">
<!ENTITY % Inline.mix
      "%Simple.class; %Simple.extra; | %Inline.class; %Inline.extra; | %Misc.class; %Misc.extra;">
<!ENTITY % Block.mix "%Block.class; %Block.extra; | %Misc.class; %Misc.extra;">
<!ENTITY % Flow.mix
       "%Simple.class; %Simple.extra; | %Inline.class; %Inline.extra;
        | %Block.class; %Block.extra; | %Misc.class; %Misc.extra;">

<!-- ======================================================================
     Math level
     Really MathML !!!
     ====================================================================== -->
<!-- Include MathML 2 -->


<!ENTITY % NS.prefixed "INCLUDE">
<!ENTITY % NamespaceDecl.attrib "xmlns:m CDATA #IMPLIED"> <!-- ??? -->
<!ENTITY % MathML.dtd PUBLIC "-//W3C//DTD MathML 2.0//EN" "mathml2.dtd">
%MathML.dtd;

<!ENTITY % Equation.extra "">

<!ELEMENT equation (XMath | tabular | punct | index %Equation.extra;)*>
<!ATTLIST equation
          label ID #IMPLIED
          refnum CDATA #IMPLIED>

<!-- Hmm, tabular ? -->
<!ENTITY % XMath.model "XMApp | XMTok | XMHint | XMArg | XMWrap | XMDual | %Simple.class;">
<!ELEMENT XMath (%XMath.model; | tabular | m:math)*>
<!ATTLIST XMath
          mode (display|inline) #IMPLIED
          tex CDATA #IMPLIED
          prefix CDATA #IMPLIED
          mathimage CDATA #IMPLIED
          width  CDATA #IMPLIED
          height CDATA #IMPLIED>

<!ELEMENT PMNode (%XMath.model;)*>
<!ATTLIST PMNode
          class CDATA #REQUIRED
          value CDATA #IMPLIED>


<!ELEMENT XMApp (%XMath.model;)*>
<!ATTLIST XMApp
          POS     CDATA #IMPLIED
          name    CDATA #IMPLIED
	  stackscripts CDATA #IMPLIED
          tex     CDATA #IMPLIED>
<!ELEMENT XMDual ((%XMath.model;), (%XMath.model;))>
<!ATTLIST XMDual
          POS     CDATA #IMPLIED
          tex     CDATA #IMPLIED>
<!ELEMENT XMTok (#PCDATA)*>
<!ATTLIST XMTok
          name    CDATA #IMPLIED
          POS     CDATA #IMPLIED
          font    CDATA #IMPLIED
          style   CDATA #IMPLIED
          size    CDATA #IMPLIED
          tex     CDATA #IMPLIED
	  stackscripts CDATA #IMPLIED>

<!ELEMENT XMHint EMPTY>
<!ATTLIST XMHint
          name    CDATA #IMPLIED
          POS     CDATA #IMPLIED
          style   CDATA #IMPLIED
          tex     CDATA #IMPLIED>

<!ELEMENT XMWrap (%XMath.model;)*>
<!ATTLIST XMWrap
          name    CDATA #IMPLIED
          POS     CDATA #IMPLIED
          style   CDATA #IMPLIED
          tex     CDATA #IMPLIED>
<!ELEMENT XMArg (%XMath.model;)*>
<!ATTLIST XMArg
          rule   CDATA #IMPLIED>

<!ELEMENT style (#PCDATA)*>
<!ATTLIST style
          style CDATA #IMPLIED>
<!ELEMENT punct (#PCDATA)*>
<!-- ======================================================================
     Document Structure
     ====================================================================== -->

<!ENTITY % Frontmatter.class "title | toctitle | author | creationdate">
<!ENTITY % Frontmatter.extra "">
<!ENTITY % Frontmatter.mix "%Frontmatter.class; %Frontmatter.extra;">

<!ENTITY % Sectitle.class "title | toctitle | author">
<!ENTITY % Sectitle.extra "">
<!ENTITY % Sectitle.mix "%Sectitle.class; %Sectitle.extra;">


<!-- If you want to rearrange the overall document structure define
     define.structure to be IGNORE, then include a modified version of
     the following. -->
<!ENTITY % define.structure  "INCLUDE" >
<![%define.structure;[

<!ELEMENT document ((%Frontmatter.mix;)*, section*, bibliography?, appendix*)>
<!ELEMENT section       ((%Sectitle.mix;)*, (%Block.mix; | subsection | paragraph)*)>
<!ELEMENT appendix      ((%Sectitle.mix;)*, (%Block.mix; | subsection | paragraph)*)>
<!ELEMENT subsection    ((%Sectitle.mix;)*, (%Block.mix; | subsubsection | paragraph)*)>
<!ELEMENT subsubsection ((%Sectitle.mix;)*, (%Block.mix; | paragraph)*)>
<!ELEMENT paragraph     ((%Sectitle.mix;)*, (%Block.mix;)*)>

]]>

<!ELEMENT title    (#PCDATA | %Inline.mix;)* >
<!ELEMENT toctitle (#PCDATA | %Inline.mix;)* >
<!ELEMENT author   (#PCDATA | %Inline.mix;)* >
<!ELEMENT creationdate (#PCDATA | %Inline.mix;)* >

<!ELEMENT p        (#PCDATA | %Inline.mix;)*>

<!ENTITY % section-attr "
          label ID #IMPLIED
          refnum CDATA #IMPLIED">

<!ATTLIST document %section-attr;>
<!ATTLIST chapter %section-attr;>
<!ATTLIST part %section-attr;>
<!ATTLIST section %section-attr;>
<!ATTLIST appendix %section-attr;>
<!ATTLIST subsection %section-attr;>
<!ATTLIST subsubsection %section-attr;>
<!ATTLIST paragraph %section-attr;>
<!-- <!ATTLIST p %section-attr;> -->

<!-- ======================================================================
     Block Elements
     ====================================================================== -->
<!ELEMENT figure (%Block.mix; | caption | toccaption)*>
<!ELEMENT table (%Block.mix; | caption | toccaption)*>
<!ATTLIST figure
          label  ID #IMPLIED
          placement CDATA #IMPLIED
          refnum CDATA #IMPLIED>
<!ATTLIST table
          label  ID #IMPLIED
          placement CDATA #IMPLIED
          refnum CDATA #IMPLIED>
<!ELEMENT caption (#PCDATA | %Inline.mix;)*>
<!ELEMENT toccaption (#PCDATA | %Inline.mix;)*>

<!-- tabular is basically cribbed from HTML4's table -->
<!ELEMENT tabular ((col*|colgroup*), thead?, tfoot?, (tbody | tr | hline)*)>
<!ATTLIST tabular
          pattern CDATA #IMPLIED
          frame   CDATA #IMPLIED
          rules   CDATA #IMPLIED>
<!ELEMENT colgroup (col)*>
<!ATTLIST colgroup
          span  CDATA #IMPLIED
          align CDATA #IMPLIED>
<!ATTLIST col
          span  CDATA #IMPLIED
          align CDATA #IMPLIED>

<!ELEMENT thead (tr)*>
<!ELEMENT tfoot (tr)*>
<!ELEMENT tbody (tr)*>
<!ELEMENT tr (td | th)*>

<!ELEMENT th (#PCDATA | %Inline.mix;)*>
<!ATTLIST th
          rowpan CDATA #IMPLIED
          colspan CDATA #IMPLIED
          align CDATA #IMPLIED
          pattern CDATA #IMPLIED>

<!ELEMENT td (#PCDATA | %Inline.mix;)*>
<!ATTLIST td
          rowspan CDATA #IMPLIED
          colspan CDATA #IMPLIED
          align CDATA #IMPLIED
          pattern CDATA #IMPLIED>

<!ELEMENT hline EMPTY>

<!ELEMENT centering (%Flow.mix;)*>
<!ELEMENT itemize (item)*>
<!ELEMENT enumerate (item)*>
<!ELEMENT description (item)*>
<!ELEMENT item (#PCDATA | tag | %Flow.mix; )*>
<!ELEMENT tag (#PCDATA | %Inline.mix;)*>

<!ELEMENT graphics EMPTY>
<!ATTLIST graphics
          graphic CDATA #REQUIRED
          options CDATA #IMPLIED
          src     CDATA #IMPLIED
          width   CDATA #IMPLIED
          height  CDATA #IMPLIED>

<!-- ======================================================================
     Inline Elements
     ====================================================================== -->
<!ELEMENT textstyle (#PCDATA | %Inline.mix;)*>
<!ATTLIST textstyle
	  font CDATA #IMPLIED>

<!ELEMENT textup (#PCDATA | %Inline.mix;)*>
<!ELEMENT textit (#PCDATA | %Inline.mix;)*>
<!ELEMENT emph   (#PCDATA | %Inline.mix;)*>
<!ELEMENT textsl (#PCDATA | %Inline.mix;)*>
<!ELEMENT textsc (#PCDATA | %Inline.mix;)*>
<!ELEMENT textmd (#PCDATA | %Inline.mix;)*>
<!ELEMENT textbf (#PCDATA | %Inline.mix;)*>
<!ELEMENT textrm (#PCDATA | %Inline.mix;)*>
<!ELEMENT textsf (#PCDATA | %Inline.mix;)*>
<!ELEMENT texttt (#PCDATA | %Inline.mix;)*>
<!ELEMENT text (#PCDATA | %Inline.mix;)*>
<!ELEMENT textsize (#PCDATA | %Inline.mix;)*>
<!ATTLIST textsize
          size CDATA #REQUIRED>


<!ELEMENT cite (citepre?,citepost?)>
<!ATTLIST cite
          ref CDATA #REQUIRED
          style (intext|parenthetic) #IMPLIED
          show CDATA #IMPLIED>
<!ELEMENT citepre (#PCDATA | %Inline.mix;)*>
<!ELEMENT citepost (#PCDATA | %Inline.mix;)*>

<!ELEMENT a  (#PCDATA | %Inline.mix;)*>
<!ATTLIST a
          href CDATA #REQUIRED>
<!-- ======================================================================
     Misc Elements
     can appear in block or inline contexts
     ====================================================================== -->

<!ELEMENT quote  (#PCDATA | %Inline.mix;)*>
<!ELEMENT footnote  (#PCDATA | %Inline.mix;)*>
<!ATTLIST footnote
          footnotemark CDATA #IMPLIED>
<!-- ======================================================================
     Meta data
     ====================================================================== -->

<!ELEMENT ref   EMPTY>
<!ATTLIST ref
          labelref CDATA #REQUIRED>
<!ELEMENT index (indexphrase*)>
<!ELEMENT indexphrase (#PCDATA | %Inline.mix;)*>

<!-- ======================================================================
     Bibliography
     ====================================================================== -->


<!ELEMENT bibliography (biblist*)>
<!ATTLIST bibliography
          files CDATA #REQUIRED>

<!ELEMENT biblist (bibentry)*>
<!-- prefix all elements with bib- to avoid conflicts
     Alternatively, separate DTD/namespace ? -->
   
<!ELEMENT bibentry (bib-author | bib-editor | bib-translator |
               bib-title | bib-subtitle | bib-booktitle |
               bib-journal | bib-series | bib-conference | bib-publisher |
               bib-organization | bib-institution | bib-address |
               bib-volume | bib-number | bib-pages | bib-part | bib-date | bib-edition |
               bib-status | bib-type |
               bib-issn | bib-doi | bib-isbn | bib-review | bib-mrnumber |
               bib-language |
               bib-url | bib-code_url | bib-eprint | bib-preprint | bib-note )*>
<!ATTLIST bibentry
          key CDATA #REQUIRED
          type CDATA #REQUIRED>
<!-- hyphenation |  xref | label | setup | name  -->

<!--
<!ELEMENT bib-author (surname, givenname?, giveninitials?, jrname?)>
<!ELEMENT bib-editor (surname, givenname?, giveninitials?, jrname?)>
<!ELEMENT surname (#PCDATA | %Inline.mix;)*>
<!ELEMENT givenname (#PCDATA | %Inline.mix;)*>
<!ELEMENT giveninitials (#PCDATA | %Inline.mix;)*>
<!ELEMENT jrname (#PCDATA | %Inline.mix;)*>
-->
<!ELEMENT bib-author (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-editor (#PCDATA | %Inline.mix;)*>

<!ELEMENT bib-translator (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-title (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-subtitle (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-booktitle (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-journal (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-series (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-conference (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-publisher (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-organization (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-institution (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-address (#PCDATA | %Inline.mix;)*>

<!ELEMENT bib-volume (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-number (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-pages (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-part (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-date (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-edition (#PCDATA | %Inline.mix;)*>

<!ELEMENT bib-status (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-type (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-issn (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-isbn (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-doi (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-review (#PCDATA | %Inline.mix; | bib-mr)*>
<!ELEMENT bib-mr (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-mrnumber (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-language (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-url (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-code_url (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-eprint (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-preprint (#PCDATA | %Inline.mix;)*>
<!ELEMENT bib-note (#PCDATA | %Inline.mix;)*>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.1.1/t/comment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class='article'?>
<?latexml package='comment'?>
<document xmlns='http://dlmf.nist.gov/LaTeXML'>
  <section>
    <p>Before Comment.
After Comment.
</p>
    <p>Before Included.
Inside Included.
After Included.
</p>
    <p>Before Excluded.
After Excluded.
</p>
    <p>Before BoldSpecial.
[<textstyle font='bold'>Inside BoldSpecial.
</textstyle>]After BoldSpecial.
</p>
    <p>Before Included.
<textstyle font='bold'>Bold Inside Included.
After Included, but still Bold.
</textstyle></p>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.1.2/t/testexpand.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class='article'?>
<document xmlns='http://dlmf.nist.gov/LaTeXML'>
  <section refnum='1'>
    <title>Testing</title>
    <p>Expecting (beep) : (beep)
</p>
    <p>Expecting (foo) : (foo)</p>
    <p>Expecting (Bar): (Bar)</p>
    <p>Expecting (BAR): BAR
</p>
    <p>Expecting (Bar): (Bar)</p>
    <p>Expecting (BAR): BAR
</p>
    <p>Expecting (BAR): BAR</p>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.1.0/t/testchar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class='article'?>
<document>
  <section refnum='1'>
    <title>Testing</title>
    <p>Testing raw tex macros: Expect inline math: xx<XMath mode='inline' tex='a+b'>
        <XMTok font='italic'>a</XMTok>
        <XMTok>+</XMTok>
        <XMTok font='italic'>b</XMTok>
      </XMath>xx </p>
    <p>Expect display math: xx</p>
    <equation>
      <XMath mode='display' tex='a+b'>
        <XMTok font='italic'>a</XMTok>
        <XMTok>+</XMTok>
        <XMTok font='italic'>b</XMTok>
      </XMath>
    </equation>
    <p>xx </p>
    <p>Expect 2 empty maths: xxa+bxx </p>
    <p>Testing latex macros Expect (onearg: one) (onearg: one) Expect (twoarg: one two) (twoarg: one ; two) Expect (twoargopt: one ; two) (twoargopt: one ; two) Expect (twoargopt: missing ; two)(twoargopt: missing ; two) </p>
    <p>Testing whitespace: Expect (twoarg: a ; b) (twoarg: a ; b) Expect (textwoarg: a ; b) (textwoarg: a ; b) Expect (twoargopt: a ; b) (twoargopt: a ; b) </p>
    <p>Expecting (beep) : (beep) </p>
    <p>Expecting (foo) : (foo)</p>
    <p>Expect [[x]] : [[x]]Expect (y(x)y) : (y(x)y) Expect [[x]] : [[x]]</p>
    <p>Expect NOW a LATER b MUCHLATER c: NOW a LATER b MUCHLATER c</p>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.5.0/t/math/testscripts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class="article"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <section>
    <para id="p1">
      <equation>
        <Math mode="display" tex="f_{a},f^{a},f_{a}^{a},f^{a}_{a}" text="Collection@(f _ a, f ^ a, SubSuperscript@(f, a, a), SubSuperscript@(f, a, a))">
          <XMath>
            <XMApp>
              <XMTok name="Collection" role="FENCED" separators=",,,"/>
              <XMApp>
                <XMTok name="Subscript" role="SUBSCRIPT"/>
                <XMTok role="UNKNOWN" font="italic">f</XMTok>
                <XMTok role="UNKNOWN" font="italic">a</XMTok>
              </XMApp>
              <XMApp>
                <XMTok name="Superscript" role="SUPERSCRIPT"/>
                <XMTok role="UNKNOWN" font="italic">f</XMTok>
                <XMTok role="UNKNOWN" font="italic">a</XMTok>
              </XMApp>
              <XMApp>
                <XMTok name="SubSuperscript"/>
                <XMTok role="UNKNOWN" font="italic">f</XMTok>
                <XMTok role="UNKNOWN" font="italic">a</XMTok>
                <XMTok role="UNKNOWN" font="italic">a</XMTok>
              </XMApp>
              <XMApp>
                <XMTok name="SubSuperscript"/>
                <XMTok role="UNKNOWN" font="italic">f</XMTok>
                <XMTok role="UNKNOWN" font="italic">a</XMTok>
                <XMTok role="UNKNOWN" font="italic">a</XMTok>
              </XMApp>
            </XMApp>
          </XMath>
        </Math>
      </equation>
    </para>
    <para id="p2">
      <equation>
        <Math mode="display" tex="{}_{a},{}^{a}">
          <XMath>
            <XMApp role="FLOATINGSUBSCRIPT">
              <XMTok role="UNKNOWN" font="italic">a</XMTok>
            </XMApp>
            <XMTok role="PUNCT">,</XMTok>
            <XMApp role="FLOATINGSUPERSCRIPT">
              <XMTok role="UNKNOWN" font="italic">a</XMTok>
            </XMApp>
          </XMath>
        </Math>
      </equation>
    </para>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.5.1/t/math/array.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class="article"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <section>
    <para id="p1">
      <p>An Array</p>
      <equation id="Ex1">
        <Math mode="display" tex="\begin{array}{ccc}a&amp;b&amp;c\\ c&amp;&amp;d\\\\ e&amp;f\\\end{array}" text="Array@(Row@(Cell@(a), Cell@(b), Cell@(c)), Row@(Cell@(c), Cell@(d)), Row@(Cell@(e), Cell@(f)))">
          <XMath>
            <XMApp role="ARRAY">
              <XMTok name="Array"/>
              <XMApp role="ARRAY">
                <XMTok name="Row"/>
                <XMApp role="ARRAY">
                  <XMTok name="Cell"/>
                  <XMTok role="UNKNOWN" font="italic">a</XMTok>
                </XMApp>
                <XMApp role="ARRAY">
                  <XMTok name="Cell"/>
                  <XMTok role="UNKNOWN" font="italic">b</XMTok>
                </XMApp>
                <XMApp role="ARRAY">
                  <XMTok name="Cell"/>
                  <XMTok role="UNKNOWN" font="italic">c</XMTok>
                </XMApp>
              </XMApp>
              <XMApp role="ARRAY">
                <XMTok name="Row"/>
                <XMApp role="ARRAY">
                  <XMTok name="Cell"/>
                  <XMTok role="UNKNOWN" font="italic">c</XMTok>
                </XMApp>
                <XMApp role="ARRAY">
                  <XMTok name="Cell"/>
                  <XMTok role="UNKNOWN" font="italic">d</XMTok>
                </XMApp>
              </XMApp>
              <XMApp role="ARRAY">
                <XMTok name="Row"/>
                <XMApp role="ARRAY">
                  <XMTok name="Cell"/>
                  <XMTok role="UNKNOWN" font="italic">e</XMTok>
                </XMApp>
                <XMApp role="ARRAY">
                  <XMTok name="Cell"/>
                  <XMTok role="UNKNOWN" font="italic">f</XMTok>
                </XMApp>
              </XMApp>
            </XMApp>
          </XMath>
        </Math>
      </equation>
      <p>Done.</p>
    </para>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.1.2/t/verb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class='article'?>
<document xmlns='http://dlmf.nist.gov/LaTeXML'>
  <section refnum='1'>
    <title>Testing Verbatim</title>
    <p>Normal <textstyle font='bold'>Bold</textstyle> stuff.
</p>
    <verbatim font='typewriter'>
AbNormal {\bf NonBold} stuff.
</verbatim>
    <p>More Normal <textstyle font='bold'>Bold</textstyle> stuff.
</p>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.1.0/t/testover.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class='article'?>
<document>
  <section refnum='1'>
    <title>Testing Over</title>
    <p><XMath mode='inline' tex='abc \over def'>
        <XMApp tex='abc \over def'>
          <XMTok name='/' style='over'/>
          <XMArg>
            <XMTok font='italic'>a</XMTok>
            <XMTok font='italic'>b</XMTok>
            <XMTok font='italic'>c</XMTok>
          </XMArg>
          <XMArg>
            <XMTok font='italic'>d</XMTok>
            <XMTok font='italic'>e</XMTok>
            <XMTok font='italic'>f</XMTok>
          </XMArg>
        </XMApp>
      </XMath> </p>
    <p><XMath mode='inline' tex='a{bc \over de}f'>
        <XMTok font='italic'>a</XMTok>
        <XMApp tex='bc \over de'>
          <XMTok name='/' style='over'/>
          <XMArg>
            <XMTok font='italic'>b</XMTok>
            <XMTok font='italic'>c</XMTok>
          </XMArg>
          <XMArg>
            <XMTok font='italic'>d</XMTok>
            <XMTok font='italic'>e</XMTok>
          </XMArg>
        </XMApp>
        <XMTok font='italic'>f</XMTok>
      </XMath> </p>
    <p><XMath mode='inline' tex='a{bc \over de}f'>
        <XMTok font='italic'>a</XMTok>
        <XMApp tex='bc \over de'>
          <XMTok name='/' style='over'/>
          <XMArg>
            <XMTok font='italic'>b</XMTok>
            <XMTok font='italic'>c</XMTok>
          </XMArg>
          <XMArg>
            <XMTok font='italic'>d</XMTok>
            <XMTok font='italic'>e</XMTok>
          </XMArg>
        </XMApp>
        <XMTok font='italic'>f</XMTok>
      </XMath> </p>
    <p><XMath mode='inline' tex='a{bc \over de}f'>
        <XMTok font='italic'>a</XMTok>
        <XMApp tex='bc \over de'>
          <XMTok name='/' style='over'/>
          <XMArg>
            <XMTok font='italic'>b</XMTok>
            <XMTok font='italic'>c</XMTok>
          </XMArg>
          <XMArg>
            <XMTok font='italic'>d</XMTok>
            <XMTok font='italic'>e</XMTok>
          </XMArg>
        </XMApp>
        <XMTok font='italic'>f</XMTok>
      </XMath> </p>
    <p><XMath mode='inline' tex='a{bc \over de}f'>
        <XMTok font='italic'>a</XMTok>
        <XMApp tex='bc \over de'>
          <XMTok name='/' style='over'/>
          <XMArg>
            <XMTok font='italic'>b</XMTok>
            <XMTok font='italic'>c</XMTok>
          </XMArg>
          <XMArg>
            <XMTok font='italic'>d</XMTok>
            <XMTok font='italic'>e</XMTok>
          </XMArg>
        </XMApp>
        <XMTok font='italic'>f</XMTok>
      </XMath> </p>
    <p><XMath mode='inline' tex='a{bc \over d \over e}f'>
        <XMTok font='italic'>a</XMTok>
        <XMApp tex='bc \over d \over e'>
          <XMTok name='/' style='over'/>
          <XMArg>
            <XMTok font='italic'>b</XMTok>
            <XMTok font='italic'>c</XMTok>
          </XMArg>
          <XMArg>
            <XMApp tex='d \over e'>
              <XMTok name='/' style='over'/>
              <XMArg>
                <XMTok font='italic'>d</XMTok>
              </XMArg>
              <XMArg>
                <XMTok font='italic'>e</XMTok>
              </XMArg>
            </XMApp>
          </XMArg>
        </XMApp>
        <XMTok font='italic'>f</XMTok>
      </XMath> <XMath mode='inline' tex='\{a\}'>
        <XMTok tex='\{'>{</XMTok>
        <XMTok font='italic'>a</XMTok>
        <XMTok tex='\}'>}</XMTok>
      </XMath> <XMath mode='inline' tex='\left\{a\right\}'>
        <XMTok POS='OPEN' tex='\left\{'>{</XMTok>
        <XMTok font='italic'>a</XMTok>
        <XMTok POS='CLOSE' tex='\right\}'>}</XMTok>
      </XMath> </p>
  </section>
</document>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.2.0/t/simplemath.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//NIST LaTeXML//LaTeXML article" "LaTeXML.dtd">
<?latexml class="article"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <section>
    <p>Inline math <Math mode="inline" tex="a+b"><XMath><XMTok font="italic">a</XMTok><XMTok role="ADDOP">+</XMTok><XMTok font="italic">b</XMTok></XMath></Math>.
</p>
    <equation>
      <Math mode="display" tex="a+b+123">
        <XMath>
          <XMTok font="italic">a</XMTok>
          <XMTok role="ADDOP">+</XMTok>
          <XMTok font="italic">b</XMTok>
          <XMTok role="ADDOP">+</XMTok>
          <XMTok name="123" role="NUMBER">123</XMTok>
        </XMath>
      </Math>
    </equation>
    <equation>
      <Math mode="display" tex="a+b+f(123)">
        <XMath>
          <XMTok font="italic">a</XMTok>
          <XMTok role="ADDOP">+</XMTok>
          <XMTok font="italic">b</XMTok>
          <XMTok role="ADDOP">+</XMTok>
          <XMTok font="italic">f</XMTok>
          <XMTok role="OPEN">(</XMTok>
          <XMTok name="123" role="NUMBER">123</XMTok>
          <XMTok role="CLOSE">)</XMTok>
        </XMath>
      </Math>
    </equation>
    <equation>
      <Math mode="display" tex="f_{D}f(a+b)">
        <XMath>
          <XMTok font="italic">f</XMTok>
          <XMApp role="POSTSUBSCRIPT">
            <XMArg rule="Subscript">
              <XMTok font="italic">D</XMTok>
            </XMArg>
          </XMApp>
          <XMTok font="italic">f</XMTok>
          <XMTok role="OPEN">(</XMTok>
          <XMTok font="italic">a</XMTok>
          <XMTok role="ADDOP">+</XMTok>
          <XMTok font="italic">b</XMTok>
          <XMTok role="CLOSE">)</XMTok>
        </XMath>
      </Math>
    </equation>
    <equation>
      <Math mode="display" tex="f_{1}(a+b)">
        <XMath>
          <XMTok font="italic">f</XMTok>
          <XMApp role="POSTSUBSCRIPT">
            <XMArg rule="Subscript">
              <XMTok role="NUMBER">1</XMTok>
            </XMArg>
          </XMApp>
          <XMTok role="OPEN">(</XMTok>
          <XMTok font="italic">a</XMTok>
          <XMTok role="ADDOP">+</XMTok>
          <XMTok font="italic">b</XMTok>
          <XMTok role="CLOSE">)</XMTok>
        </XMath>
      </Math>
    </equation>
    <equation>
      <Math mode="display" tex="\hat{f}a">
        <XMath>
          <XMApp>
            <XMTok name="hat" role="OVERACCENT">^</XMTok>
            <XMArg>
              <XMTok font="italic">f</XMTok>
            </XMArg>
          </XMApp>
          <XMTok font="italic">a</XMTok>
        </XMath>
      </Math>
    </equation>
  </section>
  <section label="sec:restricted" refnum="1">
    <title>Restricted</title>
    <equation>
      <Math mode="display" tex="a(x)+b(x)+123">
        <XMath>
          <XMTok font="italic">a</XMTok>
          <XMTok role="OPEN">(</XMTok>
          <XMTok font="italic">x</XMTok>
          <XMTok role="CLOSE">)</XMTok>
          <XMTok role="ADDOP">+</XMTok>
          <XMTok font="italic">b</XMTok>
          <XMTok role="OPEN">(</XMTok>
          <XMTok font="italic">x</XMTok>
          <XMTok role="CLOSE">)</XMTok>
          <XMTok role="ADDOP">+</XMTok>
          <XMTok name="123" role="NUMBER">123</XMTok>
        </XMath>
      </Math>
    </equation>
  </section>
</document>
