=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.4.0/t/xii.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ======================================================================
     Document type for David Carlisle's xii
     ====================================================================== -->

<!ELEMENT song (verse*)>
<!ELEMENT verse (line*)>
<!ELEMENT line (#PCDATA)>

=== freedomson/pliik/src/app/tutorial/latex-docs/LaTeXML/tags/LaTeXML-0.5.0/t/complex/xii.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE song PUBLIC "-//NIST LaTeXML//LaTeXML Poem" "xii.dtd">
<song>
  <verse>
    <line>On the first day of Christmas my true love gave to me</line>
    <line>a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the second day of Christmas my true love gave to me</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the third day of Christmas my true love gave to me</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the fourth day of Christmas my true love gave to me</line>
    <line>four calling birds</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the fifth day of Christmas my true love gave to me</line>
    <line>five gold rings</line>
    <line>four calling birds</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the sixth day of Christmas my true love gave to me</line>
    <line>six geese a laying</line>
    <line>five gold rings</line>
    <line>four calling birds</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the seventh day of Christmas my true love gave to me</line>
    <line>seven swans a swimming</line>
    <line>six geese a laying</line>
    <line>five gold rings</line>
    <line>four calling birds</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the eighth day of Christmas my true love gave to me</line>
    <line>eight maids a milking</line>
    <line>seven swans a swimming</line>
    <line>six geese a laying</line>
    <line>five gold rings</line>
    <line>four calling birds</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the ninth day of Christmas my true love gave to me</line>
    <line>nine ladies dancing</line>
    <line>eight maids a milking</line>
    <line>seven swans a swimming</line>
    <line>six geese a laying</line>
    <line>five gold rings</line>
    <line>four calling birds</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the tenth day of Christmas my true love gave to me</line>
    <line>ten lords a leaping</line>
    <line>nine ladies dancing</line>
    <line>eight maids a milking</line>
    <line>seven swans a swimming</line>
    <line>six geese a laying</line>
    <line>five gold rings</line>
    <line>four calling birds</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the eleventh day of Christmas my true love gave to me</line>
    <line>eleven pipers piping</line>
    <line>ten lords a leaping</line>
    <line>nine ladies dancing</line>
    <line>eight maids a milking</line>
    <line>seven swans a swimming</line>
    <line>six geese a laying</line>
    <line>five gold rings</line>
    <line>four calling birds</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
  <verse>
    <line>On the twelfth day of Christmas my true love gave to me</line>
    <line>twelve drummers drumming</line>
    <line>eleven pipers piping</line>
    <line>ten lords a leaping</line>
    <line>nine ladies dancing</line>
    <line>eight maids a milking</line>
    <line>seven swans a swimming</line>
    <line>six geese a laying</line>
    <line>five gold rings</line>
    <line>four calling birds</line>
    <line>three french hens</line>
    <line>two turtle doves</line>
    <line>and a partridge in a pear tree.</line>
  </verse>
</song>
